from __future__ import annotations

POSTGRES_BIGINT_MAX = (1 << 63) - 1
JSON_SAFE_INTEGER_MAX = (1 << 53) - 1
CATALOG_PRICE_MAJOR_UNIT_MAX = min(
    POSTGRES_BIGINT_MAX // 100,
    JSON_SAFE_INTEGER_MAX // 100,
)
